### ISSUE TITLE
BUG : Incompatibility with R8 Full Mode

### ISSUE THREAD

**Issue by leandrofavarin** [rudderlabs/rudder-sdk-android#210]
**Describe the bug**

The application crashes when the flag `android.enableR8.fullMode` is set to true.

<details>
<summary>Stack trace</summary>
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.rudderstack.android.sdk.core.RudderContext.updateAnonymousIdTraits()' on a null object reference
 	at com.rudderstack.android.sdk.core.RudderElementCache.updateAnonymousId(Unknown Source:5)
 	at com.rudderstack.android.sdk.core.EventRepository.updateAnonymousId(Unknown Source:17)
 	at com.rudderstack.android.sdk.core.RudderClient.putAnonymousId(Unknown Source:18)
 	at zj.g.b(Unknown Source:98)
 	at yj.o.h(Unknown Source:37)
 	at ip.a.r(Unknown Source:8)
 	at kotlinx.coroutines.k0.run(Unknown Source:108)
 	at kotlinx.coroutines.v0.i0(Unknown Source:38)
 	at kotlinx.coroutines.d0.Y(Unknown Source:168)
 	at kotlinx.coroutines.a.r0(Unknown Source:90)
 	at aa.a.O(Unknown Source:24)
 	at aa.a.P(Unknown Source:11)
 	at o.e1.a(Unknown Source:142)
 	at o.e1.H(Unknown Source:68)
 	at yl.a.<init>(Unknown Source:20)
 	at yl.b.e(Unknown Source:39)
 	at qg.c.I(Unknown Source:74)
 	at o.n0.b(Unknown Source:116)
 	at cp.w.getValue(Unknown Source:11)
 	at u1.l.a(Unknown Source:7)
 	at p3.f.a(Unknown Source:102)
 	at p3.f.A(Unknown Source:16)
 	at k0.d.A(Unknown Source:58)
 	at androidx.compose.ui.platform.z0.a(Unknown Source:24)
 	at s.x0.a(Unknown Source:66)
 	at s.x0.A(Unknown Source:95)
 	at k0.d.A(Unknown Source:58)
 	at mh.l.a(Unknown Source:183)
 	at androidx.compose.ui.platform.b1.a(Unknown Source:330)
 	at p.w.a(Unknown Source:89)
 	at p.w.A(Unknown Source:41)
 	at k0.d.A(Unknown Source:58)
 	at mh.l.a(Unknown Source:183)
 	at androidx.compose.ui.platform.j0.a(Unknown Source:538)
 	at androidx.compose.ui.platform.c3.a(Unknown Source:33)
 	at androidx.compose.ui.platform.c3.A(Unknown Source:16)
 	at k0.d.A(Unknown Source:58)
 	at mh.l.a(Unknown Source:183)
 	at androidx.compose.ui.platform.c3.a(Unknown Source:186)
 	at androidx.compose.ui.platform.c3.A(Unknown Source:28)
 	at k0.d.A(Unknown Source:58)
 	at p.b2.c(Unknown Source:325)
 	at p.b2.b(Unknown Source:183)
 	at mh.l.L(Unknown Source:42)
 	at d0.y.o(Unknown Source:124)
 	at d0.y.i(Unknown Source:13)
 	at d0.e0.k(Unknown Source:17)
 	at d0.y1.a(Unknown Source:38)
 	at d0.e0.b(Unknown Source:10)
 	at androidx.compose.ui.platform.d3.H(Unknown Source:108)
 	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(Unknown Source:11)
 	at androidx.compose.ui.platform.WrappedComposition.b(Unknown Source:13)
 	at androidx.compose.ui.platform.WrappedComposition.c(Unknown Source:18)
 	at androidx.lifecycle.x.a(Unknown Source:17)
 	at androidx.lifecycle.y.a(Unknown Source:114)
 	at androidx.compose.ui.platform.d3.H(Unknown Source:77)
 	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(Unknown Source:108)
 	at android.view.View.dispatchAttachedToWindow(View.java:20014)
 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3589)
 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2220)
 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1885)
 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8508)
 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
 	at android.view.Choreographer.doFrame(Choreographer.java:696)
 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
 	at android.os.Handler.handleCallback(Handler.java:873)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:214)
 	at android.app.ActivityThread.main(ActivityThread.java:7050)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:9
</details>

**To Reproduce**
Steps to reproduce the behaviour:

Set `android.enableR8.fullMode=true` on your `gradle.properties`.
After initialising the client, call `RudderClient.putAnonymousId("whatever")`
Expect it to crash with the above stack trace.

**Expected behavior**
The SDK should handle pro guard full mode correctly, without crashing the application.

**Version of the _Android_ SDK**
com.rudderstack.android.sdk:core:1.11.0

**SDK initialisation snippet**

```kotlin
    val rudder = RudderClient.getInstance(
      applicationContext,
      writeKey = "redacted",
      RudderConfig.Builder()
        .withDataPlaneUrl("our custom url")
        .withTrackLifecycleEvents(false)
        .build(),
    )
    RudderClient.setSingletonInstance(rudder)
```

**Check for Correct Usage of _writeKey_ and _dataPlaneUrl_**
They are correctly used.

**Comment by itsdebs** [comment]
@leandrofavarin We do not support R8 full mode yet, but we will keep this in our roadmap.

**Comment by leandrofavarin** [comment]
Today AGP 8.0 was released, and it now [includes this flag enabled by default](https://developer.android.com/build/releases/gradle-plugin#default-changes).

**Comment by desusai7** [comment]
Hey @leandrofavarin , 

Can you please try addding the proguard rules from [here](https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-android-sdk/#do-i-need-to-add-anything-to-my-proguard-rules) to your app and see if that solves the issue ?

**Comment by itsdebs** [comment]
@leandrofavarin yes, but since proguard rules are additive we want to ship it separately, may be for the next couple of releases just as a precautionary measure so that users can fine tune them. We will still be working on fine tuning these rules internally and once that is done, we will be shipping the same in consumer proguard rules.
