### ISSUE TITLE
BUG : SQLiteCantOpenDatabaseException -- Caused by android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database

### ISSUE THREAD

**Issue by sherieyu** [rudderlabs/rudder-sdk-android#218]
**Describe the bug**
From our Firebase Crashlytics, we are seeing an issue that seems to be caused by `DBPersistentManager$1.run` from the rudderstack sdk. Please check the stack trace below.

Stack Trace
```
Fatal Exception: android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/<package_name>/databases/rl_persistence.db': File /data/user/0/<package_name>databases/rl_persistence.db doesn't exist
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:254)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:935)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:915)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:772)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:761)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:373)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
       at com.rudderstack.android.sdk.core.DBPersistentManager$1.run(DBPersistentManager.java:251)
       at java.lang.Thread.run(Thread.java:1012)

Caused by android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
       at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:935)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:915)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:772)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:761)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:373)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
       at com.rudderstack.android.sdk.core.DBPersistentManager$1.run(DBPersistentManager.java:251)
       at java.lang.Thread.run(Thread.java:1012)
```

So far it is happening for a single user with 279 crash events. Here are the device details
- Android Version: Android 12
- Brand: Transsion
- Model: Tecno Pova 3 

**Version of the _Android_ SDK**
We've been using 1.8.0 for our builds. Will be releasing a new build pointed to 1.13.0 to see if it fixes the issue. Our SDK initialization is done via the main thread.

**Mobile device mode integration**
We have these integrations in place
```
const val rudderstack = "com.rudderstack.android.sdk:core:1.8.0"
const val clevertap_rudderstack = "com.rudderstack.android.integration:clevertap:1+"
const val appsflyer_sdk = "com.appsflyer:af-android-sdk:6.10.2"
const val appsflyer_rudderstack = "com.rudderstack.android.integration:appsflyer:2.2.0"
const val appsflyer_attribution = "com.android.installreferrer:installreferrer:2.1"
```

**SDK initialisation snippet**
Please provide the following information:
```
val rudderConfig = RudderConfig.Builder()
            .withDataPlaneUrl(dataUrl)
            .withTrackLifecycleEvents(true)
            .withRecordScreenViews(true)
            .withFactory(AppsFlyerIntegrationFactory.FACTORY)
            .withFactory(CleverTapIntegrationFactory.FACTORY)
            .build()
return RudderClient.Builder(appContext, analyticsKey)
            .withRudderConfig(rudderConfig).build()
```

**Check for Correct Usage of _writeKey_ and _dataPlaneUrl_**
The usage are correct since we can see the events flowing through.

**Comment by sherieyu** [comment]
I see, thanks @itsdebs! We aren't able to reproduce it. Since the time of report, no other users have experienced the crash, just this one user still.

**Comment by sherieyu** [comment]
Hi @itsdebs . We've encountered a huge volume of crash now regarding this issue. We're now at 343 crash events for 111 users at the time of writing. Seems that it happens for the brand Transsion on Android 12, Tecno Pova 3 and Camon 18 models.

Can something be done on your end? Or maybe there's a way we can somehow catch the issue and fail gracefully should this happen. We're okay with not having analytics if there's a device specific issue like this. Thanks!

**Comment by itsdebs** [comment]
@sherieyu We are looking into it. Meanwhile, can you verify 

1. If you are calling `shutdown` on rudder analytics
2. Are you using WorkManager?

**Comment by sherieyu** [comment]
Thank you @itsdebs ! To answer your questions
1. We don't call `shutdown`
2. We're not using WorkManager

**Comment by itsdebs** [comment]
@sherieyu can you check our latest release 1.17.0 and see if this exists?

**Comment by sherieyu** [comment]
Will give it a try. Thanks @itsdebs !

**Comment by sherieyu** [comment]
@itsdebs we've observed a different crash occur for our users after upgrading to 1.17.0
Please see below stack trace

So far happens on 2 users. Both on an Oppo device.

```
Fatal Exception: java.util.ConcurrentModificationException:
       at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
       at java.util.HashMap$ValueIterator.next(HashMap.java:1470)
       at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1315)
       at com.rudderstack.android.repository.RudderDatabase$init$1$2._init_$lambda$1(RudderDatabase.kt:84)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by sherieyu** [comment]
Hi @itsdebs we've reverted back to `1.13.0` for now since the above issue we encountered for `1.17.0` seems to have more volume and velocity than that of `1.13.0`. At the time we decided to revert, we were having 127 crash events affecting 123 users.

**Comment by desusai7** [comment]
Hey @tfcporciuncula, 

Can you please try addding the proguard rules from [here](https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-android-sdk/#do-i-need-to-add-anything-to-my-proguard-rules) to your app and see if that solves the issue ?

**Comment by itsdebs** [comment]
@sherieyu please use 1.20.0.

**Comment by itsdebs** [comment]
Please reopen if the issue resurfaces

**Comment by jimmydingcoins** [comment]
reopened in 1.22.0

Fatal Exception: android.database.sqlite.SQLiteCantOpenDatabaseException
Cannot open database '/data/user/0/asia.coins.mobile/databases/rl_persistence.db': File /data/user/0/asia.coins.mobile/databases/rl_persistence.db doesn't exist
android.database.sqlite.SQLiteConnection.open (SQLiteConnection.java:254)
android.database.sqlite.SQLiteConnection.open (SQLiteConnection.java:205)
android.database.sqlite.SQLiteConnectionPool.openConnectionLocked (SQLiteConnectionPool.java:505)
android.database.sqlite.SQLiteConnectionPool.open (SQLiteConnectionPool.java:206)
android.database.sqlite.SQLiteConnectionPool.open (SQLiteConnectionPool.java:198)
android.database.sqlite.SQLiteDatabase.openInner (SQLiteDatabase.java:928)
android.database.sqlite.SQLiteDatabase.open (SQLiteDatabase.java:908)
android.database.sqlite.SQLiteDatabase.openDatabase (SQLiteDatabase.java:772)
android.database.sqlite.SQLiteDatabase.openDatabase (SQLiteDatabase.java:761)
android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked (SQLiteOpenHelper.java:373)
android.database.sqlite.SQLiteOpenHelper.getWritableDatabase (SQLiteOpenHelper.java:316)
com.rudderstack.android.sdk.core.persistence.DefaultPersistence.getWritableDatabase (DefaultPersistence.java:54)
com.rudderstack.android.sdk.core.persistence.DefaultPersistence.isAccessible (DefaultPersistence.java:261)
com.rudderstack.android.sdk.core.DBPersistentManager.checkIfColumnExists (DBPersistentManager.java:487)
com.rudderstack.android.sdk.core.DBPersistentManager.lambda$checkForMigrations$2 (DBPersistentManager.java:519)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:644)
java.lang.Thread.run (Thread.java:1012)

**Comment by 1abhishekpandey** [comment]
Hey @jimmydingcoins,

Could you please open a new issue?

**Comment by jimmydingcoins** [comment]
Hello, @1abhishekpandey 
We'll first attempt to upgrade to the newest version and check if the issue can still be reproduced. If it can be reproduced, we will then open a new issue.
Thank you.

**Comment by 1abhishekpandey** [comment]
Hey @jimmydingcoins,

We would greatly appreciate it if you could provide us with the following two pieces of information:

1. Does this issue occur only when the app is in the background, or does it happen in the foreground as well?
2. Regarding the brand `Transsion` you mentioned in the issue description, does it use a custom or modified version of Android OS? Do you have any information on that?
