### ISSUE TITLE
BUG : Crash on app startup on error IllegalArgumentException: There should be at least one field in @Entity

### ISSUE THREAD

**Issue by AnnSofiAhn** [rudderlabs/rudder-sdk-android#282]
**Describe the bug**
Please provide the following information:

When using the Rudderstack Android SDK version 1.17.0 and building our app for release with `minifyEnabled true` the app crashes on startup due to the error I pasted below this. I can reproduce this creating a new, empty project in Android Studio and just building that (with our key and data plane URL in the config).

```
Caused by: java.lang.IllegalArgumentException: There should be at least one field in @Entity
at com.rudderstack.android.repository.Dao.<init>(SourceFile:51)
at com.rudderstack.android.repository.RudderDatabase.createNewDao$repository_release(SourceFile:138)
at com.rudderstack.android.repository.RudderDatabase.getDao(SourceFile:123)
at com.rudderstack.android.repository.RudderDatabase.getDao$default(SourceFile:117)
at com.rudderstack.android.ruddermetricsreporterandroid.internal.DefaultReservoir.<init>(SourceFile:47)
at com.rudderstack.android.ruddermetricsreporterandroid.DefaultRudderReporter.<init>(SourceFile:98)
at com.rudderstack.android.ruddermetricsreporterandroid.DefaultRudderReporter.<init>(SourceFile:75)
at com.rudderstack.android.ruddermetricsreporterandroid.DefaultRudderReporter.<init>(SourceFile:59)
at com.rudderstack.android.ruddermetricsreporterandroid.DefaultRudderReporter.<init>(SourceFile:50)
at com.rudderstack.android.ruddermetricsreporterandroid.DefaultRudderReporter.<init>(SourceFile:0)
at com.rudderstack.android.sdk.core.RudderClient.initiateRudderReporter(SourceFile:163)
at com.rudderstack.android.sdk.core.RudderClient.getInstance(SourceFile:155)
at com.tibber.android.app.TibberApplication.initAnalytics(SourceFile:118)
at com.tibber.android.app.TibberApplication.onCreate(SourceFile:99)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1226)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7046)
at android.app.ActivityThread.access$1800(ActivityThread.java:254) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2184) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loopOnce(Looper.java:233) 
at android.os.Looper.loop(Looper.java:344) 
at android.app.ActivityThread.main(ActivityThread.java:8212) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) 
```

Other relevant info:
Kotlin version: 1.9.0
Android Gradle Plugin: 8.2.0-alpha16

I have attached the sample where I could reproduce this, but without our credentials of course.

**To Reproduce**
Steps to reproduce the behaviour:

1. Update the Rudderstack Android SDK to 1.70.0
2. Build the app in release configuration
3. Start the app
4. See the app crash

**Expected behavior**
I would expect the app not to crash, and the SDK to make sure that any needed rules for the build are included in the SDK itself.

**Version of the _Android_ SDK**
Android SDK 1.17.0

**Mobile device mode integration**
None

**SDK initialisation snippet**
Please provide the following information:

1. Share the code snippet used for initializing the Android SDK

```kotlin
RudderClient.getInstance(
                this,
                BuildConfig.RUDDERSTACK_KEY,
                RudderConfig.Builder()
                    .withDataPlaneUrl(BuildConfig.RUDDERSTACK_URL)
                    .build(),
            ),
```

2. Indicate if the SDK initialization depends on any specific condition or event (e.g., initialization of the Android SDK after Firebase initialization or initialization in a callback)

Rudderstack is initialized after Firebase, and not in a callback.

**Check for Correct Usage of _writeKey_ and _dataPlaneUrl_**
> Confirm that the correct `writeKey` and `dataPlaneUrl` are utilized during SDK initialization.

This works in SDK version 1.16.0 so I would assume they're correct.

[MyApplication.zip](https://github.com/rudderlabs/rudder-sdk-android/files/12380273/MyApplication.zip)

**Comment by itsdebs** [comment]
@AnnSofiAhn  we are looking into it.

**Comment by AnnSofiAhn** [comment]
Thank you! Let me know if you need any more information.

**Comment by itsdebs** [comment]
Related to #280

**Comment by itsdebs** [comment]
@AnnSofiAhn We are working on creating proguard rules for Rudderstack Android SDK, we already have a ticket for this. 
Meanwhile to unblock you, you can add the following to your proguard rules file. Please let us know if you face any more issues. You can reopen this one. 

`-keep @com.rudderstack.android.repository.annotation.RudderEntity class *
-keepclassmembers class * {
    @com.rudderstack.android.repository.annotation.RudderEntity *;
}
-keepattributes RuntimeVisibleAnnotations, RuntimeVisibleParameterAnnotations

-keep class com.google.gson.reflect.TypeToken
-keep class * extends com.google.gson.reflect.TypeToken
-keep public class * implements java.lang.reflect.Type
`

**Comment by AnnSofiAhn** [comment]
Sounds great, thank you!
