### ISSUE TITLE
CRASH : Fatal Exception: java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by iamwent** [rudderlabs/rudder-sdk-android#323]
RudderStack: 1.18.1
<img width="1282" alt="image" src="https://github.com/rudderlabs/rudder-sdk-android/assets/3816024/8b9b2161-51de-47b5-b35c-17b9f98b3052">

`Fatal Exception: java.util.concurrent.RejectedExecutionException: Task jh.a@23e1a82 rejected from java.util.concurrent.ThreadPoolExecutor@58b29d0[Running, pool size = 1, active threads = 1, queued tasks = 128, completed tasks = 3]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2072)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:834)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1364)
       at com.rudderstack.android.repository.Dao.runTransactionOrDeferToCreation(Dao.kt:521)
       at com.rudderstack.android.repository.Dao.insertWithDataCallback(Dao.kt:103)
       at com.rudderstack.android.ruddermetricsreporterandroid.internal.DefaultReservoir.insertOrIncrement(DefaultReservoir.kt:61)
       at com.rudderstack.android.ruddermetricsreporterandroid.internal.metrics.DefaultAggregatorHandler.recordMetric(DefaultAggregatorHandler.kt:35)
       at com.rudderstack.android.ruddermetricsreporterandroid.metrics.LongCounter.add(Counter.kt:51)
       at com.rudderstack.android.sdk.core.ReportManager.incrementCounter(ReportManager.java:95)
       at com.rudderstack.android.sdk.core.ReportManager.incrementMessageCounter(ReportManager.java:117)
       at com.rudderstack.android.sdk.core.RudderClient.dumpMessage(RudderClient.java:534)
       at com.rudderstack.android.sdk.core.RudderClient.track(RudderClient.java:229)
       at com.rudderstack.android.sdk.core.RudderClient.track(RudderClient.java:253)
       at com.neuron.business.analytics.RudderStackAnalyzer.track(RudderStackAnalyzer.kt:100)
       at com.neuron.business.analytics.AnalyzerMgr.track(AnalyzerMgr.kt:92)
       at com.neuron.business.analytics.AnalyzerMgr.track$default(AnalyzerMgr.kt:72)
       at com.neuron.business.view.uikit.GeofenceBannerView.trackGeofencesEvent(GeofenceBannerView.kt:141)
       at com.neuron.business.view.uikit.GeofenceBannerView.renderNormalBanner(GeofenceBannerView.kt:64)
       at com.neuron.business.view.uikit.GeofenceBannerView.renderBanner(GeofenceBannerView.kt:58)
       at com.neuron.business.view.uikit.GeofenceBannerView.setCurrentGeofence(GeofenceBannerView.kt:39)
       at com.neuron.business.view.activity.HomeActivity.updateGeofenceBanner(HomeActivity.kt:1968)
       at com.neuron.business.view.activity.HomeActivity.access$getUserMapViewModel(HomeActivity.kt:81)
       at com.neuron.business.view.activity.HomeActivity.access$updateGeofenceBanner(HomeActivity.kt:81)
       at com.neuron.business.view.activity.HomeActivity$onMapClickListener$1.onZoomChanged(HomeActivity.kt:947)
       at com.neuron.business.view.component.HomeMapComponent.initMapClickListener$lambda$16(HomeMapComponent.kt:836)
       at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl$special$$inlined$observable$2.afterChange(Delegates.kt:73)
       at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
       at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.<clinit>(CameraAnimationsPluginImpl.kt:75)
       at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.setZoom(CameraAnimationsPluginImpl.kt:75)
       at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.onCameraMove(CameraAnimationsPluginImpl.kt:185)
       at com.mapbox.maps.plugin.MapPluginRegistry.onCameraMove(MapPluginRegistry.kt:153)
       at com.mapbox.maps.MapController._init_$lambda-0(MapController.kt:83)
       at com.mapbox.maps.NativeObserver.notify(NativeObserver.kt:44)
       at com.mapbox.maps.CameraManager.setCamera(CameraManager.java)
       at com.mapbox.maps.NativeMapImpl.setCamera(NativeMapImpl.kt:35)
       at com.mapbox.maps.MapboxMap.setCamera(MapboxMap.kt:413)
       at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.performMapJump$plugin_animation_publicRelease(CameraAnimationsPluginImpl.kt:250)
       at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.commitChanges(CameraAnimationsPluginImpl.kt:476)
       at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.onAnimationUpdateInternal(CameraAnimationsPluginImpl.kt:472)
       at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.access$setHighLevelAnimatorSet$p(CameraAnimationsPluginImpl.kt:38)
       at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.access$onAnimationUpdateInternal(CameraAnimationsPluginImpl.kt:38)
       at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl$registerInternalUpdateListener$1$1.invoke(CameraAnimationsPluginImpl.kt:455)
       at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl$registerInternalUpdateListener$1$1.invoke(CameraAnimationsPluginImpl.kt:455)
       at com.mapbox.maps.threading.AnimationThreadController.postOnMainThread(AnimationThreadController.kt:67)
       at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.registerInternalUpdateListener$lambda-24(CameraAnimationsPluginImpl.kt:455)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1653)
       at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1440)
       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1572)
       at android.animation.ValueAnimator.pulseAnimationFrame(ValueAnimator.java:1591)
       at android.animation.AnimatorSet.pulseFrame(AnimatorSet.java:1170)
       at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1061)
       at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:307)
       at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame()
       at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1319)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1329)
       at android.view.Choreographer.doCallbacks(Choreographer.java:930)
       at android.view.Choreographer.doFrame(Choreographer.java:854)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1303)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8805)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)`

**Comment by itsdebs** [comment]
@iamwent can you switch to 1.20.0 to check if this issue exists.
