### ISSUE TITLE
BUG : Fatal Exception: android.database.sqlite.SQLiteException: no such table: metrics (code 1 SQLITE_ERROR)

### ISSUE THREAD

**Issue by iamwent** [rudderlabs/rudder-sdk-android#328]
SDK version: 1.18.1

```
Fatal Exception: android.database.sqlite.SQLiteException: no such table: metrics (code 1 SQLITE_ERROR): , while compiling: SELECT * FROM metrics LIMIT 10
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1068)
       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:673)
       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
       at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
       at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1712)
       at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1559)
       at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1430)
       at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1636)
       at com.rudderstack.android.repository.Dao.getItems(Dao.kt:485)
       at com.rudderstack.android.repository.Dao.runGetQuerySync(Dao.kt:300)
       at com.rudderstack.android.repository.Dao$runGetQuery$1.invoke(Dao.kt:282)
       at com.rudderstack.android.repository.Dao$runGetQuery$1.invoke(Dao.kt:280)
       at com.rudderstack.android.repository.Dao.runTransactionOrDeferToCreation$lambda$26$lambda$25(Dao.kt:523)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by rwrz** [comment]
Same here. =/
Crashes spiking like crazy!

**Comment by iamwent** [comment]
Sorry, the sdk version is 1.19.1.
And I think there is some proguard rules missed in v1.19.1,  there is no live events when minify is enabled.

**Comment by itsdebs** [comment]
@iamwent @rwrz 
this is fixed in 1.20.0.

**Comment by iamwent** [comment]
@itsdebs we have already upgraded to 1.20.0 

After these crashes appear, we try catch the `rudderClient.track` method, and we'll not going to remove this try catch. So we can't verify all the crashes are fixed or not for now.

**Comment by itsdebs** [comment]
Thanks for confirming. Closing this for now. Please reopen the ticket if this resurfaces.
