### ISSUE TITLE
BUG : Fatal Exception: java.lang.NullPointerException Attempt to read from field 'java.lang.Object za.b.a' on a null object reference

### ISSUE THREAD

**Issue by AndreasBoehm** [rudderlabs/rudder-sdk-android#370]
**Describe the bug**
I just found this crash in our crashlytics dashboard.

**To Reproduce**
Can't provide steps.

**Version of the _Android_ SDK**
`Android SDK v1.21.0`

**SDK initialisation snippet**
```
apiKey?.let {
			rudderClient = RudderClient.getInstance(
				context,
				it,
				RudderConfig.Builder()
					.withDataPlaneUrl(dataPlaneUrl)
					.withTrackLifecycleEvents(true)
					.withRecordScreenViews(false)
					.withLogLevel(logLevel)
					.build()
			)
		}
```

**Stacktrace**
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.Object za.b.a' on a null object reference
       at com.rudderstack.android.sdk.core.RudderUserSessionManager.getSessionId(RudderUserSessionManager.java:76)
       at com.rudderstack.android.sdk.core.RudderUserSessionManager.applySessionTracking(RudderUserSessionManager.java:43)
       at com.rudderstack.android.sdk.core.EventRepository.processMessage(EventRepository.java:340)
       at com.rudderstack.android.sdk.core.RudderClient.dumpMessage(RudderClient.java:536)
       at com.rudderstack.android.sdk.core.RudderClient.track(RudderClient.java:223)
       at com.rudderstack.android.sdk.core.RudderClient.track(RudderClient.java:247)
```

**Comment by itsdebs** [comment]
Can you please try 1.21.1? We have fixed a race condition that might cause this issue.

**Comment by desusai7** [comment]
@AndreasBoehm, Have you tried updating to the latest version? 

And did this issue get resolved for you ?

**Comment by 1abhishekpandey** [comment]
Hey @AndreasBoehm,
I wanted to inform you that I'm closing this issue as it has been inactive for a significant period of time. While we haven't received any updates or responses regarding this issue, please know that you're always welcome to reopen it if you encounter the problem again or have any additional information to share. Your feedback is valuable to us, and we want to ensure that all issues are addressed promptly.
