### ISSUE TITLE
Velocity alert for crash due to DB insertion in Rudderstack

### ISSUE THREAD

**Issue by rohaniitr** [rudderlabs/rudder-sdk-android#72]
Receiving SQLiteException because of insertion during `execSQL()`. 
Migration to `insert()` should resolve this issue as it handles thread safety exceptions as well.

```
Fatal Exception: android.database.sqlite.SQLiteException: database is locked: INSERT INTO events (message, updated) VALUES ('{"messageId":"1626875334889-93a7c47d-77db-4a27-8e49-4d5af1ec5fc8","channel":"mobile","context":{"app":{"build":"78","name”:”XX”,”namespace”:”XXXXXXXX”,”version":"1.45.2.119"},"traits":{"anonymousId":"XXXXXXXXXXXXXXXX","id":"XXXXXXXXXXXXXXXX\u003d\u003d","userId”:”XXXXXXXXXXXXXXXX\u003d\u003d"},"library":{"name":"com.rudderstack.android.sdk.core","version":"1.0.11"},"os":{"name":"Android","version":"7.0"},"screen":{"density":480,"width":1080,"height":1920},"userAgent":"Dalvik/2.1.0 (Linux; U; Android 7.0; Lenovo K33a42 Build/NRD90N)","locale":"en-US","device":{"id":"82a2cb05f15eb81e","manufacturer":"LENOVO","model":"Lenovo K33a42","name":"K33a42","type":"Android"},"network":{"carrier":"Ind-Jio","wifi":false,"bluetooth":false,"cellular":true},"timezone":"Asia/Calcutta"},"type":"identify","originalTimestamp":"2021-07-21T13:48:54.890Z","anonymousId":"onb-c4b59574-7434-4051-8bbb-950f58f739ec","userId":"XXXXXXXXXXXXXXXX\u003d\u003d","event":"identify","integrations":{"All":true}}', 1626875334932)
       at android.database.sqlite.SQLiteDatabase.native_execSQL(SQLiteDatabase.java)
       at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2439)
       at com.rudderstack.android.sdk.core.DBPersistentManager.saveEvent(DBPersistentManager.java:53)
       at com.rudderstack.android.sdk.core.EventRepository.dump(EventRepository.java:509)
       at com.rudderstack.android.sdk.core.RudderClient.identify(RudderClient.java:324)
       at com.rudderstack.android.sdk.core.RudderClient.identify(RudderClient.java:343)
       at com.rudderstack.android.sdk.core.RudderClient.identify(RudderClient.java:352)
       at com.rudderstack.android.sdk.core.RudderClient.identify(RudderClient.java:361)
       at com.rudderstack.android.sdk.core.RudderClient.identify(RudderClient.java:372)
       at com.gamma.analytics.tools.RudderstackAnalyticsHelper.identifyUser(RudderstackAnalyticsHelper.java:87)
       at com.gamma.analytics.tools.RudderstackAnalyticsHelper.setUserIdentifier(RudderstackAnalyticsHelper.java:83)
       at com.gamma.analytics.Analytics.setUserIdentifier(Analytics.java:121)
       at com.gamma.analytics.Analytics.startSession(Analytics.java:88)
       at com.epifi.paisa.App.startAnalyticsSession(App.java:154)
       at com.epifi.paisa.App.access$startAnalyticsSession(App.java:36)
       at com.epifi.paisa.App$onCreate$2.invokeSuspend(App.java:123)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)
```

**Comment by desusai7** [comment]
Hey @rohaniitr, Thank you for raising the issue and suggesting the fix for it. We would migrate to `insert()` from `execSQL()` fixes the issue and test it out and release it.
